name: environment
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch
  - matplotlib
  - ipywidgets
  - spacy
  - jinja2
  - pip:
    - kaggle
    - transformers
    - unidecode
    - pyarrow
    - evaluate
    - rouge_score
    - fastapi
    - uvicorn
    - python-multipart
    - huggingface_hub